[package]
name = "dials-research"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.17.0"
glium = "0.31.0"
glutin = "0.28.0"
egui_glium = "0.17.0"
rand = "0.8.5"
