[package]
name = "dials-research"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.17.0"
glium = "0.31.0"
glutin = "0.28.0"
egui_glium = "0.17.0"
hound = "3.4"
rodio = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
